name: Workflow for SAST Scan 
on: push
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: maven

    - name: Build with Maven
      run: |
        mvn verify sonar:sonar \
        -Dsonar.projectKey=sonar-cloud-analysis-partone_sonar-java-project-partone \
        -Dsonar.organization=sonar-cloud-analysis-partone \
        -Dsonar.host.url=https://sonarcloud.io
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
